/* Generated By:JavaCC: Do not edit this line. LgConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LgConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROG = 6;
  /** RegularExpression Id. */
  int BEGIN = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int ENDIF = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int READ = 14;
  /** RegularExpression Id. */
  int WRITE = 15;
  /** RegularExpression Id. */
  int LOOP = 16;
  /** RegularExpression Id. */
  int ENDLOOP = 17;
  /** RegularExpression Id. */
  int ASSERT = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int BOOL = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int LPAR = 23;
  /** RegularExpression Id. */
  int RPAR = 24;
  /** RegularExpression Id. */
  int PV = 25;
  /** RegularExpression Id. */
  int DP = 26;
  /** RegularExpression Id. */
  int VIRG = 27;
  /** RegularExpression Id. */
  int AFFECT = 28;
  /** RegularExpression Id. */
  int IDF = 29;
  /** RegularExpression Id. */
  int INTPOS = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MULT = 32;
  /** RegularExpression Id. */
  int MOINS = 33;
  /** RegularExpression Id. */
  int DIV = 34;
  /** RegularExpression Id. */
  int AND = 35;
  /** RegularExpression Id. */
  int OR = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int SUP = 38;
  /** RegularExpression Id. */
  int INF = 39;
  /** RegularExpression Id. */
  int EGAL = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"program\"",
    "\"begin\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"read\"",
    "\"write\"",
    "\"loop\"",
    "\"endloop\"",
    "\"assert\"",
    "\"integer\"",
    "\"boolean\"",
    "\"true\"",
    "\"false\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\":=\"",
    "<IDF>",
    "<INTPOS>",
    "\"+\"",
    "\"*\"",
    "\"-\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
  };

}
